export const uniqueValuesDb = {
  "type": [
    "Effect Monster",
    "Flip Effect Monster",
    "Flip Tuner Effect Monster",
    "Fusion Monster",
    "Gemini Monster",
    "Link Monster",
    "Normal Monster",
    "Normal Tuner Monster",
    "Pendulum Effect Fusion Monster",
    "Pendulum Effect Monster",
    "Pendulum Effect Ritual Monster",
    "Pendulum Flip Effect Monster",
    "Pendulum Normal Monster",
    "Pendulum Tuner Effect Monster",
    "Ritual Effect Monster",
    "Ritual Monster",
    "Skill Card",
    "Spell Card",
    "Spirit Monster",
    "Synchro Monster",
    "Synchro Pendulum Effect Monster",
    "Synchro Tuner Monster",
    "Token",
    "Toon Monster",
    "Trap Card",
    "Tuner Monster",
    "Union Effect Monster",
    "XYZ Monster",
    "XYZ Pendulum Effect Monster"
  ],
  "frameType": [
    "effect",
    "effect_pendulum",
    "fusion",
    "fusion_pendulum",
    "link",
    "normal",
    "normal_pendulum",
    "ritual",
    "ritual_pendulum",
    "skill",
    "spell",
    "synchro",
    "synchro_pendulum",
    "token",
    "trap",
    "xyz",
    "xyz_pendulum"
  ],
  "race": [
    "Aqua",
    "Beast",
    "Beast-Warrior",
    "Continuous",
    "Counter",
    "Creator God",
    "Cyberse",
    "Dinosaur",
    "Divine-Beast",
    "Dragon",
    "Equip",
    "Fairy",
    "Field",
    "Fiend",
    "Fish",
    "Illusion",
    "Insect",
    "Machine",
    "Normal",
    "Plant",
    "Psychic",
    "Pyro",
    "Quick-Play",
    "Reptile",
    "Ritual",
    "Rock",
    "Sea Serpent",
    "Spellcaster",
    "Thunder",
    "Warrior",
    "Winged Beast",
    "Wyrm",
    "Zombie",

    "Abidos the Th",
    "Adrian Gecko",
    "Alexis Rhodes",
    "Amnael",
    "Andrew",
    "Arkana",
    "Aster Phoenix",
    "Axel Brodie",
    "Bastion Misaw",
    "Bonz",
    "Camula",
    "Chazz Princet",
    "Christine",
    "Chumley Huffi",
    "David",
    "Don Zaloog",
    "Dr. Vellian C",
    "Emma",
    "Espa Roba",
    "Ishizu",
    "Ishizu Ishtar",
    "Jaden Yuki",
    "Jesse Anderso",
    "Joey",
    "Joey Wheeler",
    "Kagemaru",
    "Kaiba",
    "Keith",
    "Lumis Umbra",
    "Lumis and Umb",
    "Mai",
    "Mai Valentine",
    "Mako",
    "Nightshroud",
    "Odion",
    "Paradox Broth",
    "Pegasus",
    "Rex",
    "Seto Kaiba",
    "Syrus Truesda",
    "Tania",
    "Tea Gardner",
    "The Supreme K",
    "Thelonious Vi",
    "Titan",
    "Tyranno Hassl",
    "Weevil",
    "Yami Bakura",
    "Yami Marik",
    "Yami Yugi",
    "Yubel",
    "Yugi",
    "Zane Truesdal"
  ],
  "attribute": [
    "DARK",
    "DIVINE",
    "EARTH",
    "FIRE",
    "LIGHT",
    "WATER",
    "WIND"
  ],
  "humanReadableCardType": [
    "Continuous Spell",
    "Continuous Trap",
    "Counter Trap",
    "Effect Monster",
    "Equip Spell",
    "Field Spell",
    "Flip Effect Monster",
    "Flip Tuner Effect Monster",
    "Fusion Effect Monster",
    "Fusion Monster",
    "Fusion Pendulum Effect Monster",
    "Fusion Tuner Effect Monster",
    "Fusion Tuner Monster",
    "Gemini Effect Monster",
    "Link Effect Monster",
    "Link Monster",
    "Normal Monster",
    "Normal Spell",
    "Normal Trap",
    "Pendulum Effect Monster",
    "Pendulum Flip Effect Monster",
    "Pendulum Normal Monster",
    "Pendulum Spirit Effect Monster",
    "Pendulum Tuner Effect Monster",
    "Pendulum Tuner Normal Monster",
    "Quick-Play Spell",
    "Ritual Effect Monster",
    "Ritual Monster",
    "Ritual Pendulum Effect Monster",
    "Ritual Spell",
    "Ritual Tuner Effect Monster",
    "Skill",
    "Spirit Effect Monster",
    "Synchro Effect Monster",
    "Synchro Monster",
    "Synchro Pendulum Effect Monster",
    "Synchro Tuner Effect Monster",
    "Token",
    "Toon Effect Monster",
    "Tuner Effect Monster",
    "Tuner Normal Monster",
    "Union Effect Monster",
    "Xyz Effect Monster",
    "Xyz Monster",
    "Xyz Pendulum Effect Monster"
  ]
}
